echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-27 and learning DevOps"
echo "We are learning Git and GitHub"
echo "Devops Branch created"
ehco "feature branch from EC2 machine"